name: Official Minecraft Server

on:
  workflow_dispatch:
    inputs:
      ts_authkey:
        description: "Tailscale Auth key"
        required: true

jobs:
  run-server:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ inputs.ts_authkey }}
        hostname: "mc-host"

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download & Start Server
      shell: bash
      run: |
        mkdir server && cd server
        
        # Download the official jar
        curl -o server.jar https://piston-data.mojang.com/v1/objects/64bb6d763bed0a9f1d632ec347938594144943ed/server.jar
        
        # Accept EULA
        echo "eula=true" > eula.txt
        
        # Configure Server Properties
        # view-distance: controls how many chunks the server loads
        # simulation-distance: controls how far away entities/crops update
        echo "view-distance=64" >> server.properties
        echo "simulation-distance=10" >> server.properties
        echo "max-players=10" >> server.properties
        
        # Background task to OP Syrax_x
        (
          sleep 60
          echo "op Syrax_x" > server_input
        ) &

        echo "------------------------------------------------"
        echo "SERVER IP: $(tailscale ip -4)"
        echo "RENDER DISTANCE: 64"
        echo "------------------------------------------------"
        
        # Start Server
        mkfifo server_input
        tail -f server_input | java -Xmx6G -Xms6G -jar server.jar nogui
